spring:  
  datasource:
    url: jdbc:mysql://localhost:3306/fechadinhoAuth
    username: user
    password: user
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
  hibernate:
    ddl-auto: create-only